var emp = [{
        name: "Sangami",
        age: 21,
        location: "dgl",
        vehicle: "dio",
        gender: "F",
        position: "Developer",
        doj: "2018-12-14",
        MS: "no",
    },
    {
        name: "karthiga",
        age: 24,
        domain: "js",
        location: "svg",
        vehicle: "dio",
        gender: "F",
        position: "Developer",
        doj: "2018-12-13",
        MS: "yes",
    },
    {
        name: "ajith",
        age: 20,
        domain: "js",
        location: "mdu",
        vehicle: "fz",
        gender: "M",
        position: "Developer",
        doj: "2018-12-12",
        MS: "no",
    },
    {
        name: "shanmugam",
        age: 22,
        domain: "php",
        location: "mdu",
        vehicle: "car",
        gender: "M",
        position: "Teamlead",
        doj: "2018-12-11",
        MS: "yes",
    },
    {
        name: "yogesh",
        age: 22,
        domain: "js",
        location: "svg",
        vehicle: "fz",
        gender: "M",
        positon: "Teamlead",
        doj: "2018-12-10",
        MS: "yes",
    },
    {
        name: "bala",
        age: 21,
        domain: "php",
        location: "svg",
        vehicle: "car",
        gender: "M",
        position: "Projmanager",
        doj: "2018-12-09",
        MS: "no",
    },
    {
        name: "venkat",
        age: 20,
        domain: "ios",
        location: "mdu",
        vehicle: "fz",
        gender: "M",
        position: "Projmanager",
        doj: "2018-12-08",
        MS: "no",
    },
    {
        name: "Sangami",
        age: 21,
        location: "dgl",
        vehicle: "dio",
        gender: "F",
        position: "Developer",
        doj: "2018-12-07",
        MS: "yes",
    },
    {
        name: "karthiga",
        age: 24,
        domain: "js",
        location: "svg",
        vehicle: "dio",
        gender: "F",
        position: "Developer",
        doj: "2018-12-06",
        MS: "yes",
    },
    {
        name: "akash",
        age: 20,
        domain: "js",
        location: "mdu",
        vehicle: "fz",
        gender: "M",
        position: "Developer",
        doj: "2018-12-05",
        MS: "yes",
    },
    {
        name: "shanmugam",
        age: 22,
        domain: "php",
        location: "mdu",
        vehicle: "car",
        gender: "M",
        position: "Teamlead",
        doj: "2018-12-04",
        MS: "no",
    },
    {
        name: "yogesh",
        age: 22,
        domain: "js",
        location: "svg",
        vehicle: "fz",
        gender: "M",
        position: "Teamlead",
        doj: "2018-12-03",
        MS: "yes",
    },
    {
        name: "bala",
        age: 21,
        domain: "php",
        location: "svg",
        vehicle: "car",
        gender: "M",
        position: "Projmanager",
        doj: "2018-12-02",
        MS: "yes",
    },
    {
        name: "venkat",
        age: 20,
        domain: "ios",
        location: "mdu",
        vehicle: "fz",
        gender: "M",
        position: "Projmanager",
        doj: "2018-12-01",
        MS: "yes",
    }
];
// var emp1 = emp.sort(function (a, b) {
//     return b.doj - a.doj;
// });
// console.log(emp1);

var emp3 = emp.filter(function(findstatus){
    return findstatus.MS=="yes";
    });
    console.log(emp3);
